<?php
/** @var \AHT\SalesAgent\Block\Template $block */
?>

<?php $listSales =  $block->getProducts()?>
<?= $block->getChildHtml('info') ?>
<?php if ($listSales && count($listSales)) : ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col name"><?= $block->escapeHtml(__('Product Name')) ?></th>
                    <th scope="col" class="col sku"><?= $block->escapeHtml(__('Product SKU')) ?></th>             
                    <th scope="col" class="col cmtype"><?= $block->escapeHtml(__('Commission Type')) ?></th>
                    <th scope="col" class="col cmvalue"><?= $block->escapeHtml(__('Commission Value')) ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($listSales as $listSale) : ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Product Name')) ?>" class="col name"><a href="<?= $listSale->getProductUrl()?>"><?= $listSale->getName()?></a></td>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Product SKU')) ?>" class="col sku"><?= $listSale->getSku() ?></td>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Commission Type')) ?>" class="col cmtype"><?= $listSale->getCommissionType() ?></td>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Commission Value')) ?>" class="col cmvalue"><?= $listSale->getCommissionValue() ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml(__('You have placed no orders.')) ?></span></div>
<?php endif ?>
